### ISSUE TITLE
how to get message_id

### ISSUE THREAD

**Issue by xtyorion** [ronaldborla/chikka#3]
sir how to get message_id after chikka::send() for me to compare it to notification

**Comment by ronaldborla** [comment]
$response = Chikka::send($mobile, $message);
$messageId = $response->attachments->message->id;

I have something similar in the ReadMe

**Comment by xtyorion** [comment]
yea i got it myself, thanks tho sir :))

On Sat, Feb 27, 2016 at 6:43 PM, Ronald Borla notifications@github.com
wrote:

> $response = Chikka::send($mobile, $message);
> $messageId = $response->attachments->message->id;
> 
> I have something similar in the ReadMe
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ronaldborla/chikka/issues/3#issuecomment-189617387.

## 

Regards,
Vincent Florence R. Mejorada
BSIT Student
Department of Computer and Information Science
University of San Carlos - Technological Center
