### ISSUE TITLE
unknown carrier 995

### ISSUE THREAD

**Issue by renielsalvador** [ronaldborla/chikka#8]
it throws invalid carrier when numbers starting with 0995 is entered.

**Comment by arjayads** [comment]
977 is not supported also

**Comment by arjayads** [comment]
@ronaldborla

**Comment by ronaldborla** [comment]
@renielDev @arjayads You can extend the /Chikka/Models/Carrier Class, and under chikka config, change 'carrier'=> 'Borla\Chikka\Models\Carrier' (under 'models') with your new extended Class, for example:

'carrier'=> 'MyApp\CustomCarrier'

This way you can freely override the codes() static function. You can add the new numbers there. So for 995 and 977, add them under their corresponding Networks

**Comment by arjayads** [comment]
Makes sense. Thank you..

**Comment by renielDev** [comment]
hi @ronaldborla 

Does that mean, I will need to touch the vendor files of my laravel project?

**Comment by renielsalvador** [comment]
Thanks @ronaldborla
